name: My Deploy

on:
  push:
    branches: [master]
  # pull_request:
  #   branches: [master]

jobs:
  build:
    #runs-on: defines The workflow runner
    runs-on: ubuntu-latest
    #steps: defines a series of tasks executed by the Job
    steps:
      - uses: actions/checkout@v2
      - run: | # To fetch all history for all tags and branches
          git fetch --prune --unshallow

      #Task for setting up Python 3.8 using actions/setup-python@v2 Github action
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Modify python version HERE
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install .
      - name: Pull data from Gdrive using DVC
        run: |
          dvc pull
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      - name: Run Flake8
        run: flake8
      - name: Sync model to deploy directory
        run: rsync -av model/* deploy --include="*.joblib" --exclude="*.dvc" --exclude="*.txt"
      - name: Run pytest
        run: pytest .
      # deploy:
      #   needs: build
      #   runs-on: ubuntu-latest
      #   steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_API_KEY_UDACITY_MLOPS_PROJECT_3 }}
          api-key: ${{ secrets.RENDER_SRV_KEY }}
